version: '3.8'

services:
  laravel_app:
    build: .
    container_name: laravel_app
    volumes:
      - ./laravel11docker:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  laravel_nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./laravel11docker:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - laravel_app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
